import type { OrderStatus } from "@prisma/client";

export type OrderType = "BUY" | "SELL";

const BUY_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  QUOTED: ["AWAITING_PAYMENT", "EXPIRED", "CANCELLED"],
  AWAITING_PAYMENT: ["PAYMENT_RECEIVED", "PAYMENT_CONFIRMED", "EXPIRED", "CANCELLED", "MANUAL_REVIEW"],
  PAYMENT_RECEIVED: ["AWAITING_PAYMENT", "PAYMENT_CONFIRMED", "MANUAL_REVIEW"],
  PAYMENT_CONFIRMED: ["TREASURY_SENDING", "MANUAL_REVIEW"],
  TREASURY_SENDING: ["COMPLETED", "SEND_FAILED", "TREASURY_SENDING"],
  SEND_FAILED: ["TREASURY_SENDING", "MANUAL_REVIEW"],
  MANUAL_REVIEW: ["TREASURY_SENDING", "REFUNDED"],
  COMPLETED: [],
  EXPIRED: ["MANUAL_REVIEW"],
  CANCELLED: [],
  REFUNDED: [],
  PAYMENT_FAILED: [],
  AWAITING_DEPOSIT: [],
  DEPOSIT_DETECTED: [],
  DEPOSIT_CONFIRMED: [],
  PAYOUT_PENDING: [],
  PAYOUT_PROCESSING: [],
  PAYOUT_FAILED: [],
  DEPOSIT_MISMATCH: [],
};

const SELL_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  QUOTED: ["AWAITING_DEPOSIT", "EXPIRED", "CANCELLED"],
  AWAITING_DEPOSIT: ["DEPOSIT_DETECTED", "EXPIRED", "CANCELLED"],
  DEPOSIT_DETECTED: ["DEPOSIT_CONFIRMED", "DEPOSIT_MISMATCH", "EXPIRED"],
  DEPOSIT_CONFIRMED: ["PAYOUT_PENDING", "MANUAL_REVIEW"],
  PAYOUT_PENDING: ["PAYOUT_PROCESSING"],
  PAYOUT_PROCESSING: ["COMPLETED", "PAYOUT_FAILED", "PAYOUT_PROCESSING"],
  PAYOUT_FAILED: ["PAYOUT_PROCESSING", "MANUAL_REVIEW"],
  COMPLETED: [],
  EXPIRED: ["MANUAL_REVIEW"],
  CANCELLED: [],
  MANUAL_REVIEW: ["PAYOUT_PENDING", "REFUNDED"],
  REFUNDED: [],
  AWAITING_PAYMENT: [],
  PAYMENT_RECEIVED: [],
  PAYMENT_CONFIRMED: [],
  TREASURY_SENDING: [],
  SEND_FAILED: [],
  DEPOSIT_MISMATCH: ["DEPOSIT_CONFIRMED", "MANUAL_REVIEW"],
  PAYMENT_FAILED: [],
};

export function canTransition(
  orderType: OrderType,
  from: OrderStatus,
  to: OrderStatus,
): boolean {
  const table = orderType === "BUY" ? BUY_TRANSITIONS : SELL_TRANSITIONS;
  return table[from]?.includes(to) ?? false;
}

export function getTransitions(
  orderType: OrderType,
  from: OrderStatus,
): OrderStatus[] {
  const table = orderType === "BUY" ? BUY_TRANSITIONS : SELL_TRANSITIONS;
  return table[from] ?? [];
}
